import type { MockOrder } from "./db";

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

// 15 mock orders across 10 users
// Order ID format mirrors real Ozi app (#2025605-style numerics)
// Date windows:
//   3 orders: 18–20 days ago  → eligible for trigger today
//   4 orders: 10–15 days ago  → not yet eligible
//   4 orders: 5–8 days ago    → recent, not eligible
//   4 orders: 25–30 days ago  → past window (reminder_sent = true)

export const SEED_ORDERS: Omit<MockOrder, "id">[] = [
  // ── ELIGIBLE (18–20 days ago) ──────────────────────────────────────────────
  {
    order_id: "2025610",
    user_id: "user_01",
    user_name: "Rahul Sharma",
    sku_category: "diapers",
    product_name: "Active Baby Pants, M (6-11 kg), 42 Count",
    brand: "Pampers",
    quantity: 1,
    price_inr: 799,
    image_url: null,
    delivered_at: daysAgo(19),
    reminder_sent: false,
  },
  {
    order_id: "2025611",
    user_id: "user_02",
    user_name: "Priya Mehta",
    sku_category: "diapers",
    product_name: "Extra Absorb Pants, L (9-14 kg), 54 Count",
    brand: "MamyPoko",
    quantity: 1,
    price_inr: 899,
    image_url: null,
    delivered_at: daysAgo(18),
    reminder_sent: false,
  },
  {
    order_id: "2025612",
    user_id: "user_03",
    user_name: "Ankit Verma",
    sku_category: "baby-essentials",
    product_name: "Baby Gentle Wash, 400ml",
    brand: "Himalaya",
    quantity: 2,
    price_inr: 285,
    image_url: null,
    delivered_at: daysAgo(20),
    reminder_sent: false,
  },

  // ── NOT YET ELIGIBLE (10–15 days ago) ─────────────────────────────────────
  {
    order_id: "2025613",
    user_id: "user_04",
    user_name: "Sneha Gupta",
    sku_category: "diapers",
    product_name: "Wonder Pants, XL (12-17 kg), 36 Count",
    brand: "Huggies",
    quantity: 1,
    price_inr: 749,
    image_url: null,
    delivered_at: daysAgo(12),
    reminder_sent: false,
  },
  {
    order_id: "2025614",
    user_id: "user_05",
    user_name: "Rohit Jain",
    sku_category: "baby-essentials",
    product_name: "Baby Powder, 300g",
    brand: "Johnson's",
    quantity: 2,
    price_inr: 175,
    image_url: null,
    delivered_at: daysAgo(14),
    reminder_sent: false,
  },
  {
    order_id: "2025615",
    user_id: "user_06",
    user_name: "Kavita Singh",
    sku_category: "diapers",
    product_name: "Active Baby Pants, L (9-14 kg), 54 Count",
    brand: "Pampers",
    quantity: 1,
    price_inr: 849,
    image_url: null,
    delivered_at: daysAgo(11),
    reminder_sent: false,
  },
  {
    order_id: "2025616",
    user_id: "user_07",
    user_name: "Deepak Nair",
    sku_category: "baby-essentials",
    product_name: "Mild Baby Shampoo, 150ml",
    brand: "Sebamed",
    quantity: 1,
    price_inr: 295,
    image_url: null,
    delivered_at: daysAgo(15),
    reminder_sent: false,
  },

  // ── RECENT (5–8 days ago) ──────────────────────────────────────────────────
  {
    order_id: "2025617",
    user_id: "user_08",
    user_name: "Pooja Agarwal",
    sku_category: "diapers",
    product_name: "Extra Absorb Pants, M (7-12 kg), 54 Count",
    brand: "MamyPoko",
    quantity: 1,
    price_inr: 799,
    image_url: null,
    delivered_at: daysAgo(6),
    reminder_sent: false,
  },
  {
    order_id: "2025618",
    user_id: "user_09",
    user_name: "Nikhil Rao",
    sku_category: "baby-essentials",
    product_name: "Baby Lotion, 200ml",
    brand: "Himalaya",
    quantity: 1,
    price_inr: 235,
    image_url: null,
    delivered_at: daysAgo(8),
    reminder_sent: false,
  },
  {
    order_id: "2025619",
    user_id: "user_10",
    user_name: "Meera Iyer",
    sku_category: "diapers",
    product_name: "Wonder Pants, L (9-14 kg), 42 Count",
    brand: "Huggies",
    quantity: 1,
    price_inr: 699,
    image_url: null,
    delivered_at: daysAgo(5),
    reminder_sent: false,
  },
  {
    order_id: "2025620",
    user_id: "user_01",
    user_name: "Rahul Sharma",
    sku_category: "baby-essentials",
    product_name: "Baby Soap Bar, 75g (Pack of 4)",
    brand: "Dove Baby",
    quantity: 1,
    price_inr: 320,
    image_url: null,
    delivered_at: daysAgo(7),
    reminder_sent: false,
  },

  // ── PAST WINDOW (25–30 days ago) — reminder already sent ──────────────────
  {
    order_id: "2025606",
    user_id: "user_02",
    user_name: "Priya Mehta",
    sku_category: "diapers",
    product_name: "Active Baby Pants, M (6-11 kg), 42 Count",
    brand: "Pampers",
    quantity: 1,
    price_inr: 799,
    image_url: null,
    delivered_at: daysAgo(28),
    reminder_sent: true,
  },
  {
    order_id: "2025607",
    user_id: "user_04",
    user_name: "Sneha Gupta",
    sku_category: "baby-essentials",
    product_name: "Baby Gentle Wash, 400ml",
    brand: "Himalaya",
    quantity: 2,
    price_inr: 285,
    image_url: null,
    delivered_at: daysAgo(26),
    reminder_sent: true,
  },
  {
    order_id: "2025608",
    user_id: "user_06",
    user_name: "Kavita Singh",
    sku_category: "diapers",
    product_name: "Extra Absorb Pants, XL (12-17 kg), 36 Count",
    brand: "MamyPoko",
    quantity: 1,
    price_inr: 849,
    image_url: null,
    delivered_at: daysAgo(25),
    reminder_sent: true,
  },
  {
    order_id: "2025609",
    user_id: "user_08",
    user_name: "Pooja Agarwal",
    sku_category: "baby-essentials",
    product_name: "Baby Powder, 300g",
    brand: "Johnson's",
    quantity: 2,
    price_inr: 175,
    image_url: null,
    delivered_at: daysAgo(30),
    reminder_sent: true,
  },
];
